config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check


  resources :experiences, only: [:new,:create, :update, :destroy]
  resources :searches, only: [:show, :new, :create, :update, :destroy] do
    collection do
      get :init, as: :init
    end
  end
  resources :favorites, only: [:create, :destroy]

  resources :chatrooms, only: [:new, :show, :create] do
    resources :messages, only: [:create]
  end

  get '/dashboard_searches', to: 'pages#dashboard_searches', as: :dashboard_searches
  get '/dashboard_favorites', to: 'pages#dashboard_favorites', as: :dashboard_favorites
  get '/dashboard_profile', to: 'pages#dashboard_profile', as: :dashboard_profile
  get '/dashboard_chatrooms', to: 'pages#dashboard_chatrooms', as: :dashboard_chatrooms
  get '/dashboard_chatrooms_unread', to: 'pages#dashboard_chatrooms_unread', as: :dashboard_chatrooms_unread
  post '/dashboard_searches/:search_id/details/:user_id', to: 'searches#details', as: :search_details

  # Defines the root path route ("/")
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  belongs_to :user_1, class_name: "User", foreign_key: :user_1_id
  belongs_to :user_2, class_name: "User", foreign_key: :user_2_id
  has_many :messages, dependent: :destroy

  validates :user_1_id, uniqueness: { scope: :user_2_id, message: "Chatroom already exists between these users" }

  def participants
    [user_1, user_2]
  end

  def other_user(current_user)
    current_user == user_1 ? user_2 : user_1
  end

  # def self.ordered_by_last_message
  #   left_joins(:messages)
  #     .group(:id)
  #     .order('MAX(messages.created_at) DESC NULLS LAST')
  # end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :set_chatroom, only: [:show]


  def index
    @chatrooms = current_user.chatrooms
  end

  def show
    @message = Message.new
    @users = User.where.not(id: current_user.id)
    @chatrooms = Chatroom.where("user_1_id = :user_id OR user_2_id = :user_id", user_id: current_user.id)
    @chatroom.messages.where(sender: @chatroom.other_user(current_user), reading: false).update_all(reading: true)
  end

  def new
    @chatroom = Chatroom.new
    @chatroom.find_by(user_1: current_user, user_2: @user)

  end

  def create
    if Chatroom.find_by(user_1: current_user, user_2_id: params[:chatroom][:recipient_id])
      redirect_to dashboard_chatrooms_path(@chatroom), notice: 'Chatroom was successfully found.'
    else
      @chatroom = Chatroom.new(chatroom_params)
      @chatroom.user_1 = current_user
      @chatroom.user_2 = User.find(params[:chatroom][:recipient_id])
      if @chatroom.save
        Message.create!(chatroom: @chatroom, sender: current_user, content: params[:chatroom][:message])
        redirect_to dashboard_searches_path, notice: 'Message successfully sent.'
      else
        redirect_to dashboard_searches_path, alert: "Impossible de créer la conversation"
      end
    end
  end

  private

  def set_chatroom
    @chatroom = Chatroom.find(params[:id])
    unless @chatroom.user_1 == current_user || @chatroom.user_2 == current_user
      redirect_to root_path, alert: "You don't have access to this chat"
    end
  end

  def chatroom_params
    params.require(:chatroom).permit(:name, :user_2_id)
  end
end

app/views/chatrooms/_new_chatroom_modal.html.erb
<div class="modal fade"
     id="newChatroomModal-<%= @user.id %>"
     tabindex="-1"
     aria-labelledby="newChatroomModal-<%= @user.id %>Label"
     aria-hidden="true">
     <div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
  <h5 class="modal-title" id="newChatroomModal-<%= @user.id %>Label">Message</h5>
  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>

<% @chatroom = Chatroom.find_by(user_1: current_user, user_2: @user) || Chatroom.new %>

<%= form_with(
      model: @chatroom,
      url: chatrooms_path,
      local: true,
      data: { controller: "chatroom", turbo: false },
      method: :post
    ) do |f| %>
  <div class="modal-body">
    <div class="mb-3">
      <%= f.text_field :message,
          class: "form-control",
          placeholder: "Votre message...",
          required: true
      %>
    </div>
    <%= f.hidden_field :recipient_id, value: @user.id if @user %>
    <%#= f.hidden_field :user_2_id, value: @user.id %>
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
    <%= f.submit "Envoyer", class: "btn btn-primary" %>
  </div>
<% end %>

  </div>
</div>

</div>

app/views/chatrooms/index.html.erb
<%# le link de l'icone nouveau chatroom
<%= link_to 'New Chatroom', new_chatroom_path %>

app/views/chatrooms/new.html.erb
<div class="modal fade"
     id="newChatroomModal"
     tabindex="-1"
     aria-labelledby="newChatroomModalLabel"
     aria-hidden="true">
     <div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
  <h5 class="modal-title" id="newChatroomModalLabel">Message</h5>
  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<%= form_with(
      model: @chatroom,
      url: chatrooms_path,
      local: true,
      data: { controller: "chatroom", turbo: false },
      method: :post
    ) do |f| %>
  <div class="modal-body">
    <div class="mb-3">
      <%= f.text_area :message,
          class: "form-control",
          placeholder: "écrivez votre message ici...",
          rows: 3,
          required: true
      %>
    </div>
    <%= f.hidden_field :recipient_id, value: @user.id if @user %>
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
    <%= f.submit "Envoyer", class: "btn btn-primary" %>
  </div>
<% end %>

  </div>
</div>

</div>

app/views/chatrooms/show.html.erb
<%= turbo_frame_tag "chatroom_content" do %>
  <div class="chat">
    <%= turbo_stream_from [@chatroom, current_user, "messages"] %>
    <div id="messages" class="messages">
      <% @chatroom.messages.each do |message| %>
        <%= render "messages/message", message: message, user: current_user %>
      <% end %>
    </div>

    <div class="message-form bg-white sticky-bottom">
      <%= simple_form_for [@chatroom, @message],
          html: {class: "d-flex w-100"},
          data: { turbo_stream: true,
                 controller: "reset-form",
                 action: "turbo:submit-end->reset-form#reset" } do |f| %>
        <%= f.input :content,
          label: false,
          placeholder: "Écrivez un message...",
          wrapper_html: {class: "flex-grow-1"},
          input_html: {class: "bg-transparent"}
        %>
        <%= f.button :submit, "Envoyer", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
<% end %>